version: "3"

services:
  torch:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../:/root/workspace/
      - ../../datasets:/root/datasets/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.ssh:/root/.ssh
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      QT_X11_NO_MITSHM: 1
    stdin_open: true
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
